semantic error: Unhashable type in dict: 'slice'
 --> tests/errors/test_dict7.py:4:11
  |
4 |     print(d[1:2])
  |           ^^^^^^ 
